providers:
  - id: my-ta-api
    baseUrl: https://tds-virtual-ta-1pw1.onrender.com/api/  # 🔁 Replace with your actual Render URL

scenarios:
  - name: "Token cost with Japanese text"
    provider: my-ta-api
    prompts:
      - prompt: "How much would the input token cost for gpt-3.5-turbo-0125 if I use the Japanese text?"
        assert:
          - type: contains
            value: "cost"

  - name: "Fallback for unclear question"
    provider: my-ta-api
    prompts:
      - prompt: "What’s the square root of banana?"
        assert:
          - type: contains
            value: "couldn’t identify"
