providers:
  - ./my-ta-provider.js:myTaProvider

scenarios:
  - name: Token Cost Test
    provider: my-ta-api
    tests:
      - vars:
          prompt: "How much would the input token cost for gpt-3.5-turbo-0125 if I use the Japanese text?"